### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by blindndangerous** [jmdaweb/NVDARemoteServer#19]
Would it be possible to add in support for Let's Encrypt for SSL setup? https://letsencrypt.org/

**Comment by jmdaweb** [comment]
Hello.
I use letsencrypt on some of my domains, and I like it very much. Unfortunately, it doesn't make much sense here, because ssl is used with encryption purposes, and not to verify server identity.
I recommend reading NVDARemoteServer.conf (5) man page. If you want to use your letsencrypt certificate, you must concatenate the private key, the certificate and the certification authority in the same file, then update the pemfile setting in the configuration file.
Regards.
