### ISSUE TITLE
Debian 8 package: make python3 (not python) a dependancy

### ISSUE THREAD

**Issue by codeofdusk** [jmdaweb/NVDARemoteServer#39]
The current Debian8 package depends on Python 2.7, but the script seems to be able to run on 3.x. Change the python dependancy to python3.

**Comment by tech10** [comment]
To my knowledge, Python 3 is not included in the default Debian 8 repositories. Changing the package build for Debian 8 to Python 3 might complicate the process of installation on this version of the operating system.

Debian 9 and above seem to have support for Python 3 by default, and Debian 8 was end of life on June 30 of 2020. I would recommend dropping support for Debian 8 and supporting Debian 9 and above by default, changing the package build to use Python 3 and install on nothing below Debian 9, if possible.

Also, Python 2 reached its end of life when 2020 began, using Python 3 by default on as many builds as possible might not be an unreasonable course of action, and at some point, Python 2 support should probably be dropped.

**Comment by jmdaweb** [comment]
Hi,
I will change the folder names soon. Instead of debian7 and debian8, they may be called debian-non-systemd or debian-containers, and debian-systemd, as these are their actual purposes. The debian7 package is currently used for the Docker container and similar technologies, and the debian8 is used for Debian, Ubuntu, etc. with systemd installed and working.
"python" has been kept as a dependency in hopes all systems install Python 3 in the future when you request Python, as Arch Linux currently does. However, given the current situation, this will change in the next version.
Regards.

**Comment by jmdaweb** [comment]
Hi again,
The main change has been performed and commited. Once I build and test the package on all affected platforms, this issue will be closed. Note that ArchLinux installs Python3 by default when Python is requested, and the main executable is also called python instead of python3. Python3 will be used on Centos 7 too.
Regards.
