### ISSUE TITLE
Buggy performance on Windows

### ISSUE THREAD

**Issue by leonardder** [jmdaweb/NVDARemoteServer#7]
I've installed NVDA remote server on a windows PC, but it seems to be quite buggy. It uses about 50% of cpu resources, and in windows service mode the performance of remote connections is quite poor. Any thoughts on this? I assume it shouldn't be a problem that we're using an x86 server on an x64 pc?

**Comment by jmdaweb** [comment]
Hello.
You should use the x64 version if you are running a x64 system. It’s faster than x86 version.
The code is as optimized as possible, all performance problems are caused by Python.
From: Leonard de Ruijter 
Sent: Saturday, June 11, 2016 12:54 PM
To: Technow-es/NVDARemoteServer 
Subject: [Technow-es/NVDARemoteServer] Buggy performance on Windows (#7)

I've installed NVDA remote server on a windows PC, but it seems to be quite buggy. It uses about 50% of cpu resources, and in windows service mode the performance of remote connections is quite poor. Any thoughts on this? I assume it shouldn't be a problem that we're using an x86 server on an x64 pc?

**Comment by leonardder** [comment]
So, do I understand it correctly that running an x86 build on Windows 
x64 could cause this kind of major cpu usage regressions? Wouldn't that 
also apply to NVDA itself than?

**Comment by jmdaweb** [comment]
NVDA is built with some c++ libraries, which are much more eficient than pure Python. We don’t know how much cpu would NVDA use if it was 100% Python code.

**Comment by leonardder** [comment]
I've been running the x64-variant now, but I still get occasional high cpu usage.

**Comment by jmdaweb** [comment]
Hello again.
Test the latest commit. If the CPU usage is still high, reopen the issue and let me know.
