### ISSUE TITLE
make an  option to   let us choose on what port the server will run on instead of forcing  the default one 

### ISSUE THREAD

**Issue by hamzalatif7** [jmdaweb/NVDARemoteServer#8]
Not sure if this a problem but thought I would suggest hear. would it be possible for this server to let the user give a custom port  it could be an option that you could give at the command line when starting the server  if no option is given it should use the default port. The reason on why I am suggesting this because it would help to get around port blocking  that companies use  so when i connect to college to   the server to another computer to control  it should work.

**Comment by jmdaweb** [comment]
Hello.
I will add a config file in the next version to change listening interface and port.
Regards.

From: hamzalatif7
Sent: Thursday, January 26, 2017 1:00 PM
To: jmdaweb/NVDARemoteServer
Cc: Subscribed
Subject: [jmdaweb/NVDARemoteServer] make an option to let us choose on what port the server will run on instead of forcing the default one (#8)


Not sure if this a problem but thought I would suggest hear. would it be possible for this server to let the user give a custom port it could be an option that you could give at the command line when starting the server if no option is given it should use the default port. The reason on why I am suggesting this because it would help to get around port blocking that companies use so when i connect to college to the server to another computer to control it should work.
